source 'http://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'omniauth', git: 'git@github.com:anildigital/omniauth.git'
gem 'omniauth-foursquare'
gem 'rest-client'
gem 'foursquare2', git: 'https://github.com/anildigital/foursquare2'
gem 'byebug'
